### PR TITLE
Added support for Laravel 5.3

### PR DESCRIPTION
**Pull request by wout**

### CODE REVIEW

**Comment by bostanio** [comment]
dupe of #24

**Comment by wout** [comment]
Thanks! Although I'm still getting the error messages when installing with composer:

```cli
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove illuminate/database v5.3.4
    - Conclusion: don't install illuminate/database v5.3.4
    - nanigans/single-table-inheritance 0.6.0 requires illuminate/database 5.2.* -> satisfiable by illuminate/database[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - nanigans/single-table-inheritance 0.6.1 requires illuminate/database 5.2.* -> satisfiable by illuminate/database[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - Can only install one of: illuminate/database[v5.2.0, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.19, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.21, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.24, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.25, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.26, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.27, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.28, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.31, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.32, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.37, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.43, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.45, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.6, v5.3.4].
    - Can only install one of: illuminate/database[v5.2.7, v5.3.4].
    - Installation request for illuminate/database (locked at v5.3.4, required as ^5.2) -> satisfiable by illuminate/database[v5.3.4].
    - Installation request for nanigans/single-table-inheritance 0.6.* -> satisfiable by nanigans/single-table-inheritance[0.6.0, 0.6.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by bostanio** [comment]
you probably need 0.7.0 which was just released.

**Comment by wout** [comment]
Brilliant, many thanks!

**Pull request closed without merging**
