### PR TITLE
Add support for laravel 5.5

### LINKED ISSUE #36: Support for Laravel 5.5
Hello,

I tried to make a pull-request for Laravel 5.5, but I can't figure out how to make the test-cases succeed. Before I made any changes, I ran ```vendor/bin/phpunit``` which gave no errors. Then I made the following changes to ```composer.json```:
- Added 5.5.* to lluminate/database and lluminate/support.
- Added ~6.0 to phpunit/phpunit
- Updated orchestra/testbench to 3.5.*

It looks like the migrations are not executed, I've read the documentation on orchestra/testbench, but I don't understand why the migrations are not running.

### PR DESCRIPTION
**Pull request by tobiasdierich**
This PR adds support for laravel 5.5.

Closes #36

### CODE REVIEW

**Comment by RobertBoes** [comment]
The be() function in tests/TestCase.php seems unnecessary?

```php
/**
 * Set the currently logged in user for the application.
 *
 * @param  \Illuminate\Contracts\Auth\Authenticatable $user
 * @param  string                                     $driver
 *
 * @return void
 */
public function be(Authenticatable $user, $driver = null)
{
  //
}
```

I tested and my tests work correctly without this function

**Comment by tobiasdierich** [comment]
Woops. For some reason phpstorm told me "Implement be() or mark your test cases as abstract". Fixed in 9fad4ee

**Comment by RobertBoes** [comment]
I don't see any reason why this fails now, looks like php 5.5 is suddenly not installed?

**Comment by tobiasdierich** [comment]
Probably just have to restart the build. Looks like the download of php 5.5 timed out (took 310s instead of ~15s)

**Comment by zagreusinoz** [comment]
Looks like @tobiasdierich is right.  Can we run the tests again?  I would really like to have this working with 5.5.

**Comment by LarsZondag** [comment]
What's the status on this PR right now, @tobiasdierich? Would really like to have the 5.5 support.

**Comment by tobiasdierich** [comment]
@LarsZondag imho this can be merged, I've actually been using my fork in a 5.5 app and had no problems so far. However, since I don't have write access to this repo we have to wait until someone with write access restarts ci and merges this...

**Comment by RedAB** [comment]
Hi, is there any contributor ready to do it ? I would like to upgrade my Laravel application to 5.5 but this is the last remaining package blocking the process. Thanks !

**Pull request merged**
