### PR TITLE
Allow numerical type values

### PR DESCRIPTION
**Pull request by fedpet**
For better performance and smaller database size

### CODE REVIEW

**Comment by bostanio** [comment]
Can we add a test case to prove the desire behavior?

**Comment by fedpet** [comment]
Is it ok now?

**Comment by jbbr** [comment]
Is there any reason why this is not being merged?
It's working fine for me

**Comment by bostanio** [comment]
What is the actual change here? It looks like there is a Mongo change but that orthogonal to supporting numeric types. What didn't work before?

**Comment by jbbr** [comment]
@bostanio I assume this line is the relevant: https://github.com/Nanigans/single-table-inheritance/pull/28/files#diff-af590ee72356412161aa86ba9c250e86L65
At least that's the only change which is not mongo specific nor testing.

Without this PR numeric types didn't work with MySQL for me. I don't remember what actually didn't work but I'm basically doing what's in the new tests in this branch. So If these tests pass in the current master the underlying problem would have already been fixed.

**Comment by slowpokefarm** [comment]
When using numeric type values, array_merge drops actual numeric keys in current implementation. +1 for this PR.

**Comment by bostanio** [comment]
Can we strip out the mongo changes?

**Comment by bostanio** [comment]
Covered more simply by #49.

**Pull request closed without merging**
